[section]
key = "amazon_analysis"
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#FFC300"  # A slightly brighter, more vibrant gold
backgroundColor = "#111111"  # Dark, but not pure black for better contrast
secondaryBackgroundColor = "#1A1A1A" # Slightly lighter than background for depth
textColor = "#EEEEEE"      # Light gray for excellent contrast on dark background
font = "sans serif"

[server]
enableCORS = false  # Keep this as needed for your setup
enableXsrfProtection = true # Important for security

[browser]
gatherUsageStats = false #  Respect user privacy
